default: &default
  adapter: mysql2
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myarticles
  username: root
  password: root

test:
  <<: *default
  database: myarticles

production:
  <<: *default
  database: myarticles
